#!/usr/bin/env bash
# redirect to a link in the location lordy.tech/redirect_me/

sudo apt update
sudo apt install -y nginx

sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
link="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;"
sudo sed -i "9i $link" /etc/nginx/sites-available/default

sudo service nginx reload
