#!/usr/bin/env bash
# install and configure HAproxy on lb-01 server.

sudo apt-get -y update
sudo apt-get install -y haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
echo "ENABLED=1" >> /etc/default/haproxy

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn     4000
    user        haproxy
    group       haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 50000
    timeout server 50000

listen alx
    bind *:80
    balance roundrobin
    server web-01 100.26.53.140:80 check
    server web-02 100.26.244.194:80 check
" > /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
sudo systemctl enable haproxy
