#!/usr/bin/env bash
# Nginx likes port 80
sed -i 's/listen [0-9]\+/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:[0-9]\+/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
pkill -o nginx
